server {
    listen 80;
    # server_name 是 Nginx 用于虚拟主机（Virtual Host）的配置，它决定了 Nginx 应该处理哪个域名的请求。
    server_name localhost;

    # 1. 托管 React 打包后的静态资源
    # `/` 代表**匹配所有请求**
    location / {
        # 静态文件根目录，就是我们 Dockerfile 复制过来的 dist 打包产物。
        root /usr/share/nginx/html;
        # 访问文件夹时默认打开 index.html。
        index index.html index.htm;
        # 1. `$uri`：先去磁盘找这个文件；
        # 2. `$uri/`：找不到就尝试当做文件夹；
        # 3. 都找不到，**强制返回 `/index.html`**
        try_files $uri $uri/ /index.html; # 支持 React Router 路由刷新
    }

    # 2. 将 /api 开头的请求反向代理到 Python 后端容器
    location /api/ {
        # 不带结尾 /，以保留后端路由所需的 /api 前缀。
        # `app‑server` 是 docker compose 网络 DNS 域名，直接访问另外一个容器
        proxy_pass http://app-server:8000;
        proxy_http_version 1.1;
        # Ollama 大模型流式返回 SSE，必须关闭缓冲，否则页面收不到实时一字一字的输出，会全部等完一次性返回
        proxy_buffering off;
        proxy_read_timeout 3600s;
        proxy_set_header Host $host;
        # 把真实客户端 IP 传给 python 后端，否则后端拿到的是 nginx 容器内网 IP
        proxy_set_header X-Real-IP $remote_addr;
        # 传递完整客户端链路 IP
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}